#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

remove_shims_from_path()
{
  local IFS=:

  paths=($PATH)
  for i in ${!paths[@]}; do
    if [ ${paths[i]} = "$(exec genv root)/shims" ]; then
      unset 'paths[i]'
    fi
  done

  echo "${paths[*]}"
}

if [ -n "$CUDA_VISIBLE_DEVICES" ]; then
  set -- "--id=$CUDA_VISIBLE_DEVICES" "$@"
fi

PATH="$(remove_shims_from_path)" nvidia-smi "$@"
