#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Add genv support to your shell"
    exit 0
fi

if [ "$1" = "-" ]; then
  sh_commands=(`genv-commands --sh`)
  cf_commands=(`genv-commands --cf`)

  IFS="|"
  cat <<EOS
_genv_config()
{
  local command="\${1:-}"

  case "\$command" in
  ${cf_commands[*]})
    if [ "\$#" -gt 0 ]; then
      shift
    fi

    local subcommand="\${1:-}"
    case "\$subcommand" in
    show)
      command genv "cf-\$command" "\$@"
      ;;
    load|*)
      eval "\$(command genv "cf-\$command" "\$@")"
      ;;
    esac
    ;;
  load)
    eval "\$(command genv config "\$@")"
    ;;
  show|*)
    command genv config "\$@"
    ;;
  esac
}

_genv_sh()
{
  local command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  eval "\$(command genv "sh-\$command" "\$@")"
}

genv()
{
  local command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${sh_commands[*]})
    _genv_sh "\$command" "\$@"
    ;;
  config)
    _genv_config "\$@"
    ;;
  *)
    command genv "\$command" "\$@"
    ;;
  esac

  # TODO(raz): preserve the exit code of failed 'eval' commands
}
EOS
else
  if [ "$1" = "--warn" ]; then
    echo "WARNING: Your shell is not yet set up to use genv."
    echo
  fi

  echo 'Run this for your shell to support genv.'
  echo 'You should add it to your ~/.bashrc or any equivalent file.'
  echo
  echo '    eval "$(genv init -)"'
  echo
fi
