#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Device count"
  exit 0
fi

config_env()
{
  if [ -n "$1" ]; then
    cat <<EOS
_genv_set_env GENV_GPUS $1
EOS
  else
    cat <<EOS
_genv_unset_env GENV_GPUS
EOS
  fi
}

do_print()
{
  prefix=${GENV_CONFIG_PRINT_PREFIX:+gpus\: }
  target=${GENV_CONFIG_PRINT_TARGET:-\&\1}

  cat <<EOS
if [ -n "\$GENV_GPUS" ]; then
  echo "$prefix\$GENV_GPUS" >$target
fi
EOS
}

do_clear()
{
  ( exec genv exec envs config --eid $GENV_ENVIRONMENT_ID gpus --clear )

  config_env
}

do_refresh()
{
  gpus=$( exec genv exec envs query --eid $GENV_ENVIRONMENT_ID --query config.gpus )

  config_env $gpus
}

do_config()
{
  ( exec genv exec envs config --eid $GENV_ENVIRONMENT_ID gpus --count $1 )

  config_env $1
}

case $1 in
  ''|--print)
    do_refresh
    do_print
  ;;
  --clear)    do_clear     ;;
  --refresh)  do_refresh   ;;
  *)          do_config $1 ;;
esac
