#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Print this help message"
    exit 0
fi

command_path() {
  local command="$1"
  command -v genv-"$command" || command -v genv-sh-"$command"
}

echo "Usage: genv <command>"
echo
echo "Available commands:"
for command in $(exec genv-commands); do
    printf "    %-10s    %s\n" "$command" "$(exec $(command_path $command) --description)"
done
echo
