#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Display the directory containing the configuration of this environment"
    exit 0
fi

( exec genv exec home "$@" )
