#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Run a genv executable"
    exit 0
fi

print_executables()
{
  shopt -s nullglob

  {
    for executable_path in "$GENV_ROOT/exe/genv-"*; do
      echo "    ${executable_path##*genv-}"
    done
  } | sort | uniq
}

print_help()
{
  echo "Usage: genv exec <executable> [-h|--help]"
  echo
  echo "Executables:"
  print_executables
  echo
}

print_help_and_fail()
{
  print_help >&2
  exit 1
}

command="$1"
case "$command" in
"")
  print_help_and_fail
  ;;
-h|--help)
  print_help
  ;;
*)
  executable=$command
  shift

  path="$GENV_ROOT/exe/genv-$executable"

  if [ ! -f "$path" ]; then
    {
      echo "No such executable '$executable'"
      echo
      print_help_and_fail
    } >&2
  fi

  exec $path "$@"
  ;;
esac
