#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Environment name"
  exit 0
fi

config_env()
{
  if [ -n "$1" ]; then
    cat <<EOS
_genv_set_env GENV_ENVIRONMENT_NAME "$1"
_genv_set_env PS1 "(genv:$1) \${GENV_BACKUP_ENV_PS1-}"
EOS
  else
    cat <<EOS
_genv_unset_env GENV_ENVIRONMENT_NAME
_genv_set_env PS1 "(genv) \${GENV_BACKUP_ENV_PS1-}"
EOS
  fi
}

do_print()
{
  prefix=${GENV_CONFIG_PRINT_PREFIX:+name\: }
  target=${GENV_CONFIG_PRINT_TARGET:-\&\1}

  cat <<EOS
if [ -n "\$GENV_ENVIRONMENT_NAME" ]; then
  echo "$prefix\$GENV_ENVIRONMENT_NAME" >$target
fi
EOS
}

do_clear()
{
  ( exec genv exec envs config --eid $GENV_ENVIRONMENT_ID name --clear )

  config_env
}

do_refresh()
{
  name=$( exec genv exec envs query --eid $GENV_ENVIRONMENT_ID --query config.name )

  config_env "$name"
}

do_config()
{
  ( exec genv exec envs config --eid $GENV_ENVIRONMENT_ID name --name "$1" )

  config_env "$1"
}

case $1 in
  ''|--print)
    do_refresh
    do_print
  ;;
  --clear)    do_clear       ;;
  --refresh)  do_refresh     ;;
  *)          do_config "$1" ;;
esac
