#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Environment gpu memory"
  exit 0
fi

config_env()
{
  if [ -n "$1" ]; then
    cat <<EOS
_genv_set_env GENV_GPUS_MEMORY $1
EOS
  else
    cat <<EOS
_genv_unset_env GENV_GPUS_MEMORY
EOS
  fi
}

do_print()
{
  prefix=${GENV_CONFIG_PRINT_PREFIX:+gpu_memory\: }
  target=${GENV_CONFIG_PRINT_TARGET:-\&\1}

  cat <<EOS
if [ -n "\$GENV_GPUS_MEMORY" ]; then
  echo "$prefix\$GENV_GPUS_MEMORY" >$target
fi
EOS
}

do_clear()
{
  ( exec genv exec envs config --eid $GENV_ENVIRONMENT_ID gpu_memory --clear )

  config_env
}

do_refresh()
{
  gpu_memory=$( exec genv exec envs query --eid $GENV_ENVIRONMENT_ID --query config.gpu_memory )

  config_env "$gpu_memory"
}

do_config()
{
  ( exec genv exec envs config --eid $GENV_ENVIRONMENT_ID gpu_memory --gpu_memory "$1" )

  config_env "$1"
}

case $1 in
  ''|--print)
    do_refresh
    do_print
  ;;
  --clear)    do_clear       ;;
  --refresh)  do_refresh     ;;
  *)          do_config "$1" ;;
esac
