#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Obtain exclusive access to a device"
  exit 0
fi

print_help()
{
  echo "Usage: genv lock <index> command [arguments]"
  echo
  echo "Execute a command under an exclusive lock of a device."
  echo "This command works very similarly to flock(1)."
  echo
  echo "Example:"
  echo
  echo "  genv lock 0 bash -c \"echo using device; sleep 5; echo done using device\""
  echo
}

command="$1"
case "$command" in
"")
  print_help >&2
  exit 1
  ;;
-h|--help)
  print_help
  ;;
*)
  index=$command
  shift

  # first, use the Python library to get the lock path.
  # this also create the file and its parent directories with the right permissions if needed.
  path=$( exec /usr/bin/env python3 -c "import genv.devices; print(genv.devices.get_lock_path($index))" )

  # now actually obtain an exclusive lock and run the command
  exec flock "$path" "$@"
  ;;
esac
