#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Run a genvctl command"
    exit 0
fi

if ! command -v genvctl &> /dev/null
then
  # we manually set the system path if the Genv Python package is not installed.
  # this is for backward compatability with installation from source.
  exec env PYTHONPATH=$GENV_ROOT/py:$PYTHONPATH python3 -m genv.ctl "$@"
else
  exec genvctl "$@"
fi
