#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Add genv support to your shell"
    exit 0
fi

if [ "$1" = "-" ]; then
  sh_commands=(`genv-commands --sh`)
  cf_commands=(`genv-commands --cf`)

  IFS="|"
  cat <<EOS
genv()
{
  local command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${sh_commands[*]})
    eval "\$(command genv "sh-\$command" "\$@")"
    ;;
  config)
    eval "\$(command genv config "\$@")"
    ;;
  *)
    command genv "\$command" "\$@"
    ;;
  esac

  # TODO(raz): preserve the exit code of failed 'eval' commands
}

if [ "\$GENV_PREACTIVATE" = "1" ]; then
  command="genv activate"

  if [ "\$GENV_PREACTIVATE_PROMPT" = "0" ]; then
    command="\$command --no-prompt"
  fi

  if [ -n "\$GENV_PREACTIVATE_GPUS" ]; then
    command="\$command --gpus \$GENV_PREACTIVATE_GPUS"
  fi

  if [ -n "\$GENV_PREACTIVATE_ENVIRONMENT_NAME" ]; then
    command="\$command --name \$GENV_PREACTIVATE_ENVIRONMENT_NAME"
  fi

  eval "\$command"
fi
EOS
else
  if [ "$1" = "--warn" ]; then
    echo "WARNING: Your shell is not yet set up to use genv."
    echo
  fi

  echo 'Run this for your shell to support genv.'
  echo 'You should add it to your ~/.bashrc or any equivalent file.'
  echo
  echo '    eval "$(genv init -)"'
  echo
fi
