#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Show status of the current environment"
  exit 0
fi

if [ -z "$GENV_ENVIRONMENT_ID" ] ; then
  echo "Environment is not active"
else
  echo "Environment is active ($GENV_ENVIRONMENT_ID)"
  if [ "$CUDA_VISIBLE_DEVICES" = "-1" ]; then
    echo "Detached from GPUs"
  else
    echo "Attached to GPUs at indices $CUDA_VISIBLE_DEVICES"
  fi
  echo
  echo "Configuration"
  echo "    Name: ${GENV_ENVIRONMENT_NAME:-N/A}"
  echo "    Device count: ${GENV_GPUS:-N/A}"
  echo
fi
