#!/bin/bash

set -e
[ -n "$GENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "List all available genv commands"
    exit 0
fi

if [ "$1" = "--sh" ]; then
  sh="1"
elif [ "$1" = "--cf" ]; then
  cf="1"
fi

shopt -s nullglob

{
  for command_path in "$GENV_ROOT/libexec/genv-"*; do
    command="${command_path##*genv-}"

    if [ "$cf" = "1" ]; then
      if [ "${command:0:3}" = "cf-" ]; then
        echo "${command##cf-}"
      fi
    elif [ "$sh" = "1" ]; then
      if [ "${command:0:3}" = "sh-" ]; then
        echo "${command##sh-}"
      fi
    else
      if [ ! "${command:0:3}" = "cf-" ]; then
        echo "${command##sh-}"
      fi
    fi
  done
} | sort | uniq
