#!/bin/bash

set -e
[ -n "$RNENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Add rnenv support to your shell"
    exit 0
fi

if [ "$1" = "-" ]; then
  sh_commands=(`rnenv-commands --sh`)
  cf_commands=(`rnenv-commands --cf`)

  IFS="|"
  cat <<EOS
_rnenv_config()
{
  local command="\${1:-}"

  case "\$command" in
  ${cf_commands[*]})
    if [ "\$#" -gt 0 ]; then
      shift
    fi

    local subcommand="\${1:-}"
    case "\$subcommand" in
    show)
      command rnenv "cf-\$command" "\$@"
      ;;
    load|*)
      eval "\$(command rnenv "cf-\$command" "\$@")"
      ;;
    esac
    ;;
  load)
    eval "\$(command rnenv config "\$@")"
    ;;
  show|*)
    command rnenv config "\$@"
    ;;
  esac
}

_rnenv_sh()
{
  local command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  eval "\$(command rnenv "sh-\$command" "\$@")"

  if [ "\$command" = "activate" ]; then
    rnenv config load
  fi
}

rnenv()
{
  local command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${sh_commands[*]})
    _rnenv_sh "\$command" "\$@"
    ;;
  config)
    _rnenv_config "\$@"
    ;;
  *)
    command rnenv "\$command" "\$@"
    ;;
  esac

  # TODO(raz): preserve the exit code of failed 'eval' commands
}
EOS
else
  if [ "$1" = "--warn" ]; then
    echo "WARNING: Your shell is not yet set up to use rnenv."
    echo
  fi

  echo 'Run this for your shell to support rnenv.'
  echo 'You should add it to your ~/.bashrc or any equivalent file.'
  echo
  echo '    eval "$(rnenv init -)"'
  echo
fi
