#!/bin/bash

set -e
[ -n "$RNENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Activate managed environment"
    exit 0
fi

if [ -n "$RNENV_ACTIVATED" ] ; then
    echo "Already running in managed environment" 1>&2
    exit 1
fi

cat <<EOS
export RNENV_BACKUP_LD_LIBRARY_PATH="\$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RNENV_ROOT/lib:\$LD_LIBRARY_PATH"

export RNENV_BACKUP_PS1="\${PS1-}"
export PS1="(rnenv) \${PS1-}"

export RNENV_ACTIVATED=1;
EOS
