#!/bin/bash

set -e
[ -n "$RNENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Activate environment"
  exit 0
fi

if [ -n "$RNENV_ENVIRONMENT_ID" ] ; then
  echo "Already running in an active environment" 1>&2
  exit 1
fi

cat <<EOS
_rnenv_append_env()
{
  # based on https://unix.stackexchange.com/a/415028
  export \$1="\${!1:+\${!1}:}\$2"
}

_rnenv_backup_env()
{
  if [ -n "\${!1}" ]; then
    export RNENV_BACKUP_ENV_\$1="\${!1}"
    _rnenv_append_env RNENV_BACKUP_ENVS \$1
  fi
}

_rnenv_set_env()
{
  export \$1="\$2"
  _rnenv_append_env RNENV_ENVS \$1
}

_rnenv_unset_env()
{
  unset \$1
}

_rnenv_replace_env()
{
  _rnenv_backup_env \$1
  _rnenv_set_env \$1 "\$2"
}

_rnenv_set_env RNENV_ENVIRONMENT_ID \$\$
_rnenv_replace_env PATH "$RNENV_ROOT/shims:\$PATH"
_rnenv_replace_env PYTHONPATH "$RNENV_ROOT/py:\$PYTHONPATH"
_rnenv_replace_env PS1 "(rnenv) \${PS1-}"

( exec rnenv exec envs activate --pid \$\$ --eid \$RNENV_ENVIRONMENT_ID )
EOS
