#!/bin/bash

set -e
[ -n "$RNENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
  echo "Configure this environment"
  exit 0
fi

print_command()
{
  printf "    %-5s    %s\n" "$1" "$2"
}

print_config_commands()
{
  print_command "load" "Load configuration from disk"
}

print_subcommands()
{
  for command in $(exec rnenv-commands --cf); do
    print_command "$command" "$(exec $(command -v "rnenv-cf-$command") --description)"
  done
}

print_commands()
{
  echo "Available commands:"
  print_config_commands
  print_subcommands
}

print_help()
{
  echo "Usage: rnenv config <command> [-h|--help]"
  echo
  print_commands
  echo
}

command="$1"
case "$command" in
"")
  print_help >&2
  exit 1
  ;;
load)
  home="$(exec rnenv-home --quiet)"
  if [[ -n "$home" ]]; then
    shopt -s nullglob
    for file in "$home/"*; do
      ( exec rnenv cf-${file##*/} --load )
    done
  fi
  ;;
-h|--help)
  print_help
  ;;
*)
  {
    if [ -n "$(command -v "rnenv-cf-$command" || true)" ]; then
      ( exec rnenv init --warn )
    else
      echo "No such config command '$command'"
      echo
      print_commands
      echo
    fi
  } >&2
  exit 1
  ;;
esac
