#!/bin/bash

set -e
[ -n "$RNENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Add rnenv support to your shell"
    exit 0
fi

if [ "$1" = "-" ]; then
  commands=(`rnenv-commands --sh`)
  IFS="|"
  cat <<EOS
rnenv() {
  local command
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(rnenv "sh-\$command" "\$@")"
    ;;
  *)
    command rnenv "\$command" "\$@"
    ;;
  esac
}
EOS
else
  echo 'Run this for your shell to support rnenv.'
  echo 'You should add it to your ~/.bashrc or any equivalent file.'
  echo
  echo '    eval "$(rnenv init -)"'
  echo
fi
