#!/bin/bash

set -e
[ -n "$RNENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Print this help message"
    exit 0
fi

command_path() {
  local command="$1"
  command -v rnenv-"$command" || command -v rnenv-sh-"$command"
}

echo "Usage: rnenv <command>"
echo
echo "Available commands:"
for command in $(exec rnenv-commands); do
    printf "    %-10s    %s\n" "$command" "$(exec $(command_path $command) --description)"
done
echo
