#!/bin/bash

set -e
[ -n "$RUNAI_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "List all available runai commands"
    exit 0
fi

if [ "$1" = "--sh" ]; then
  sh="1"
fi

shopt -s nullglob

{
  for command_path in "$RUNAI_ROOT/libexec/runai-"*; do
    command="${command_path##*runai-}"
    if [ "$sh" = "1" ]; then
      if [ "${command:0:3}" = "sh-" ]; then
        echo "${command##sh-}"
      fi
    else
      echo "${command##sh-}"
    fi
  done
} | sort | uniq
