#!/bin/bash

set -e
[ -n "$RUNAIENV_DEBUG" ] && set -x

export RUNAIENV_ROOT=${RUNAIENV_ROOT:-"$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/.."}
export PATH="$RUNAIENV_ROOT/libexec:$PATH"

command="$1"
case "$command" in
"" )
  runaienv-help >&2
  exit 1
  ;;
-h | --help )
  exec runaienv-help
  ;;
* )
  command_path="$(command -v "runaienv-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ -n "$(command -v "runaienv-sh-$command" || true)" ]; then
      {
        echo "Your shell is not yet set up to use runaienv."
        echo "Run this for instructions:"
        echo
        echo "    runaienv init"
        echo
      } >&2
    else
      echo "No such command '$command'" >&2
    fi
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
