#!/bin/bash

set -e
[ -n "$RUNAIENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Print this help message"
    exit 0
fi

command_path() {
  local command="$1"
  command -v runaienv-"$command" || command -v runaienv-sh-"$command"
}

echo "Usage: runaienv <command>"
echo
echo "Available commands:"
for command in $(exec runaienv-commands); do
    printf "    %-9s    %s\n" "$command" "$(exec $(command_path $command) --description)"
done
echo
