#!/bin/bash

set -e
[ -n "$RUNAIENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Deactivate managed environment"
    exit 0
fi

if [ -z "$RUNAIENV_ACTIVATED" ] ; then
    echo "Not running in managed environment" 1>&2
    exit 1
fi

cat <<EOS
export LD_LIBRARY_PATH="\$RUNAIENV_BACKUP_LD_LIBRARY_PATH"
unset RUNAIENV_BACKUP_LD_LIBRARY_PATH

export PS1=\$RUNAIENV_BACKUP_PS1
unset RUNAIENV_BACKUP_PS1

unset RUNAIENV_ACTIVATED
EOS
