#!/bin/bash

set -e
[ -n "$RUNAIENV_DEBUG" ] && set -x

if [[ $1 = "--description" ]] ; then
    echo "Activate managed environment"
    exit 0
fi

if [ -n "$RUNAIENV_ACTIVATED" ] ; then
    echo "Already running in managed environment" 1>&2
    exit 1
fi

cat <<EOS
export RUNAIENV_BACKUP_LD_LIBRARY_PATH="\$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$RUNAIENV_ROOT/lib:\$LD_LIBRARY_PATH"

export RUNAIENV_BACKUP_PS1="\${PS1-}"
export PS1="(runaienv) \${PS1-}"

export RUNAIENV_ACTIVATED=1;
EOS
