#!/usr/bin/env python3

import argparse
from datetime import datetime
from typing import Any, Dict, List

import genv

JSON = 'envs.json'
DATETIME_FMT = '%d/%m/%Y %H:%M:%S'

Env = Dict[Any, Any]
Envs = Dict[int, Env]

QUERIES = {
    'eid': lambda env: env["eid"],
    'name': lambda env: env["name"] if "name" in env else None,
    'creation': lambda env: env["created"],
}

def cleanup(envs: Envs) -> None:
    # cleanup terminated processes
    for env in envs.values():
        env["pids"] = [pid for pid in env["pids"] if genv.poll(pid)]

    # cleanup terminated environments
    for eid in [eid for eid, env in envs.items() if len(env["pids"]) == 0]:
        del envs[eid]

def do_activate(envs: Envs, pid: int, eid: int, uid: int, username: str) -> None:
    if eid not in envs:
        envs[eid] = dict(
            eid=eid,
            uid=uid,
            username=username,
            created=datetime.now().strftime(DATETIME_FMT),
            pids=[],
        )

    env: Env = envs[eid]

    if pid not in env["pids"]:
        env["pids"].append(pid)

def deactivate(envs: Envs, eid: int, pid: int) -> None:
    env: Env | None = envs.get(eid)

    if env is not None:
        while pid in env["pids"]:
            env["pids"].remove(pid)

        if len(env["pids"]) == 0:
            del envs[eid]

def rename(env: Env, name: str | None) -> None:
    if name is None:
        if "name" in env:
            del env["name"]
    else:
        env["name"] = name

def do_ps(envs: Envs, header: bool=True) -> None:
    if header:
        print('ID      USER            NAME            CREATED              PID(S)')

    for env in envs.values():
        eid = env["eid"]
        user = f'{env["username"]}({env["uid"]})'
        name = env.get("name", '')
        created = genv.time_since(datetime.strptime(env["created"], DATETIME_FMT))
        pids = ','.join(str(pid) for pid in env["pids"])

        print(f'{eid:<8}{user:<16}{name:<16}{created:<21}{pids}')

def do_query(envs: Envs, eid: int | None, queries: List[str]) -> None:
    eids = [eid] if eid is not None else list(envs.keys())

    for eid in eids:
        env = envs.get(eid)

        if env is None:
            continue

        query = lambda name: str(QUERIES[name](env) or '')

        print(','.join(query(name) for name in queries))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=f'genv environment manager')
    parser.add_argument('--no-cleanup', dest='cleanup', action='store_false', help='Do not perform clean up')
    parser.add_argument('--reset', action='store_true', help='Reset previous state')

    subparsers = parser.add_subparsers(dest='command', required=True)

    parser_activate = subparsers.add_parser('activate', help='Activate a new process')
    parser_activate.add_argument('--pid', type=int, required=True, help='PID')
    parser_activate.add_argument('--eid', type=int, required=True, help='Environment ID')
    parser_activate.add_argument('--uid', type=int, required=True, help='User ID')
    parser_activate.add_argument('--username', required=True, help='User name')

    parser_deactivate = subparsers.add_parser('deactivate', help='Deactivate a process')
    parser_deactivate.add_argument('--pid', type=int, required=True, help='PID of the deactivated process')
    parser_deactivate.add_argument('--eid', type=int, help='Environment ID')

    parser_rename = subparsers.add_parser('rename', help='Rename an environment')
    parser_rename.add_argument('--eid', type=int, required=True, help='Environment ID')
    parser_rename.add_argument('--name', help='Environment name')

    parser_ps = subparsers.add_parser('ps', help='Print information about active environments')
    parser_ps.add_argument('--no-header', dest='header', action='store_false', help='Do not print column headers')

    parser_query = subparsers.add_parser('query', help='Query environments')
    parser_query.add_argument('--eid', type=int, help='Environment ID')
    parser_query.add_argument('--query', '--queries', dest='queries', nargs='+', choices=QUERIES.keys(), required=True)

    args = parser.parse_args()

    if genv.exists(JSON) and not args.reset:
        json = genv.read(JSON)

        # we need to convert environment ids to integers. they are saved as
        # strings because dictionary keys in json files must be strings.
        json["envs"] = { int(eid): env for eid, env in json["envs"].items() }
    else:
        json = dict(
           envs=dict(),
        )

    envs: Envs = json["envs"]

    if args.cleanup:
        cleanup(envs)

    if args.command == 'activate':
        do_activate(envs, args.pid, args.eid, args.uid, args.username)
    elif args.command == 'deactivate':
        pid = args.pid
        eid = args.eid or pid

        deactivate(envs, eid, pid)
    elif args.command == 'rename':
        env: Env = envs.get(args.eid)

        if env is not None:
            rename(env, args.name)
    elif args.command == 'ps':
        do_ps(envs, args.header)
    elif args.command == 'query':
        do_query(envs, args.eid, args.queries)

    genv.save(JSON, json)
